version: "3.5"
services:
  database_master:
    image: mysql:8.0.30
    container_name: "database_master"
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mysqldata_master:/var/lib/mysql
      - ./master.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_USER=db_user
      - MYSQL_DATABASE=my_db_users
      - MYSQL_PASSWORD=S3cret
    networks:
      - mynetwork
  database_slave:
    image: mysql:8.0.30
    container_name: "database_slave"
    restart: unless-stopped
    depends_on:
      - database_master
    ports:
      - 3307:3306
    volumes:
      - mysqldata_slave:/var/lib/mysql
      - ./slave.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_USER=db_user
      - MYSQL_DATABASE=my_db_users
      - MYSQL_PASSWORD=S3cret
    networks:
      - mynetwork
  database_todo:
    image: mysql:8.0.30
    container_name: "database_todo"
    restart: unless-stopped
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_USER=db_user
      - MYSQL_DATABASE=my_db_todos
      - MYSQL_PASSWORD=S3cret
    volumes:
      - "./init_todo.sql:/docker-entrypoint-initdb.d/1.sql"
networks:
  mynetwork:
volumes:
  mysqldata_master:
  mysqldata_slave:
